//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChuyenBay
    {
        public int MaCB { get; set; }
        public int SanBayTrungGian { get; set; }
        public int ThoiGianDung { get; set; }
        public int TGToiThieu { get; set; }
        public int TGToiDa { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SanBay SanBay { get; set; }
        public virtual ChuyenBay ChuyenBay { get; set; }
    }
}
