//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoNgoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoNgoi()
        {
            this.VeChuyenBays = new HashSet<VeChuyenBay>();
        }
    
        public int MaGhe { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public Nullable<int> MaCB { get; set; }
        public Nullable<int> MaHangVe { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual HangVe HangVe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeChuyenBay> VeChuyenBays { get; set; }
    }
}
