//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuBanVe
    {
        public int MaDoanhThu { get; set; }
        public Nullable<int> MaCB { get; set; }
        public int SoVe { get; set; }
        public float TyLe { get; set; }
        public int DoanhThu { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
    }
}
