//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuNam
    {
        public int MaDoanhThuNam { get; set; }
        public int Thang { get; set; }
        public int SoChuyenBay { get; set; }
        public int DoanhThu { get; set; }
        public float TyLe { get; set; }
    }
}
