//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeChuyenBay
    {
        public int MaVeCB { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<int> MaGhe { get; set; }
    
        public virtual ChoNgoi ChoNgoi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
